apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
# property-like keys; each key maps to a simple value
    FLASK_APP: "FLASK_APP"
    FLASK_DEBUG: "TRUE"
    MONGODB_DATABASE: "openings"
    MONGODB_USERNAME: "root"
    MONGODB_PASSWORD: "pass"
    MONGODB_HOSTNAME: "{{ .Release.Name }}-mongodb"
    MONGODB_PORT: "27017"
#file-like keys
  # application.properties: |
  #   server.port = 80
  #   spring.application.name = democrm